### ISSUE TITLE
Error 'Sorry, you don't have permission to run this program' in HOOBS

### ISSUE THREAD

**Issue by BarnicleFiend** [wibberryd/homebridge-rpi-rts#1]
I'm running RPI-RTS in HOOBS but I'm struggling to set up root privilege. 

I've created the homebridge.service and home bridge files with the content advised but they don't appear to be giving home bridge root privilege and I suspect things may be slightly different on HOOBS.

Does anyone know how to correct this? Log extract below.

23/05/2020, 15:58:48 2020-05-23 08:58:48 initCheckPermitted:
23/05/2020, 15:58:48 +---------------------------------------------------------+
23/05/2020, 15:58:48 |Sorry, you don't have permission to run this program.    |
23/05/2020, 15:58:48 |Try running as root, e.g. precede the command with sudo. |
23/05/2020, 15:58:48 +---------------------------------------------------------+
23/05/2020, 15:58:48 Error loading plugin "homebridge-rpi-rts".
23/05/2020, 15:58:48 Error: pigpio error -1 in gpioInitialise
    at initializePigpio (/home/hoobs/.hoobs/node_modules/pigpio/pigpio.js:29:12)
    at new Gpio (/home/hoobs/.hoobs/node_modules/pigpio/pigpio.js:133:5)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-rpi-rts/RpiGpioRts.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-rpi-rts/index.js:1:20)

**Comment by KoenVoortman** [comment]
Hello, I have the exact same problem.
I put HOOBS on a new microSD card, started fresh. And can't get it to work :( 

Please help us out!

**Comment by wibberryd** [comment]
Hello, I know this is very frustrating, I also ran into this kind of problems for a long time before getting the solution with the service files from online communities.

Unfortunately, I don't have access to a HOOBS device to try, and I have limited knowledge with Linux.

All I can advise is to double check the files `/etc/systemd/system/homebridge.service` and `/etc/default/homebridge`.

On my Raspberry Pi, `sudo cat /etc/systemd/system/homebridge.service` gives:
```
[Unit]
Description=Homebridge
Wants=network-online.target
After=syslog.target network-online.target

[Service]
WorkingDirectory=/var/lib/homebridge
EnvironmentFile=/etc/default/homebridge
ExecStartPre=/bin/run-parts /etc/hb-service/homebridge/prestart.d
ExecStartPre=/usr/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js before-start $HOMEBRIDGE_OPTS
ExecStart=/usr/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js run $HOMEBRIDGE_OPTS
# Maybe better to use default KillMode=control-group? Then comment next line.
KillMode=process

[Install]
WantedBy=multi-user.target
```

And `sudo cat /etc/default/homebridge` gives:
```
HOMEBRIDGE_OPTS=-I -U "/var/lib/homebridge" --allow-root
UIX_STORAGE_PATH="/var/lib/homebridge"

# To enable web terminals via homebridge-config-ui-x uncomment the following line
HOMEBRIDGE_CONFIG_UI_TERMINAL=1

DISABLE_OPENCOLLECTIVE=true
```

As you mention, it could also be that HOOBS devices have additional security measures that prevent to give root access to Homebridge.

I am sorry to not be able to help you further on this issue, and hope you will find a solution.

**Comment by AragornSRB** [comment]
When i tried to install plugin in HOOBS i got lucky and install it without changing this file completely /etc/systemd/system/homebridge.service

I just changed in that file Users=hoobs to Users=root   

My problem was different and i installed homebridge because i thought that problem was in Hoobs.  wibberryd solved my problem with version 1.0.2 .

hope this helped

**Comment by KoenVoortman** [comment]
I’ve got the recent version of the plug-in installed and not throwing errors. 😃 
I can see the switches in Homebridge and HomeKit. 
Got the transmitter changed with the other saw resonator. But nothing happens when I try to program the remote. 
I’ve got an exact 17cm antenna from the board... I’ve even got it to about 50cm from the shutter but still nothing. 

I even made another one (second transmitter board and other resonator). But no difference. 

I also don’t see anything in the log when I press any button in Homebridge UI or HomeKit. 

What can be the problem? 

![B6E1BF1E-B2BD-4941-A7BA-BEA3AE18041C](https://user-images.githubusercontent.com/60989130/107864443-6ece6a00-6e5c-11eb-9634-3952cc6c3b8a.jpeg)
![51E3B7C3-3E87-44CA-9039-E6C72FA7DF62](https://user-images.githubusercontent.com/60989130/107864444-70982d80-6e5c-11eb-80d2-a85881b33703.jpeg)

**Comment by wibberryd** [comment]
1) Have you enabled debug mode in Homebridge? (From Config-UI-X, go to Settings, and turn on Homebridge Debug Mode -D, then restart Homebridge).

The logs from the plugin appear only in debug mode. Once enabled, you should see something similar to this each time you press a button:
```
[2/14/2021, 8:00:00 AM] [Name_Of_Your_Device] Function setOn called for button Up with value true
[2/14/2021, 8:00:00 AM] [Name_Of_Your_Device] Function sendCommand with id: 12345, rolling code: 25 and button: Up
[2/14/2021, 8:00:01 AM] [Name_Of_Your_Device] Saved rolling code 26 in file ./12345.txt
[2/14/2021, 8:00:01 AM] [Name_Of_Your_Device] Function resetSwitchWithTimeout called for button Up
[2/14/2021, 8:00:02 AM] [Name_Of_Your_Device] Function setOn called for button Up with value false
```

2) When you try to program the remote, after you press on the Prog button of the current remote (the one that you use to control the shutter usually), does the shutter jog (moves up and down)?

3) On the photos, the wiring looks correct. I don't see any problem there. I have the same transmitter, and I soldered the antenna at the same place. So if everything else is working, maybe one of the pins on the Raspberry Pi is not working?
- Try using another pin for the +5V and the Ground ([https://www.raspberrypi.org/documentation/usage/gpio/](https://www.raspberrypi.org/documentation/usage/gpio/))
- If it still doesn't work, try using another pin for the Data. You will need to change the number of the GPIO pin used in the file `RpiGpioRts.js`: `sudo nano $(npm -g prefix)/lib/node_modules/homebridge-rpi-rts/RpiGpioRts.js`. Change the value on the line 5: `const outPin = 4;`, then `Ctrl + O` to save and `Ctrl + X` to exit. Restart Homebridge.

**Comment by KoenVoortman** [comment]
Hi, thanks for the reply.
1. I've got the debug working, and the same code appears in the log now. So that's working.
2. yes, that works fine.
3. I will try that. Does outPin need the GPIO number or the actual PIN number? So I have to choose another GPIO. So if I choose 17, I will have put the wire on pin 11. (see picture for reference/example).

![raspberry_pi_circuit_note_fig2](https://user-images.githubusercontent.com/60989130/107879275-218fde00-6ed8-11eb-8b11-e1988ec6ea66.jpg)

**Comment by wibberryd** [comment]
Yes, outPin needs the GPIO number. So as you say, if you write `const outPin = 17;`, put the wire on the pin 11.

**Comment by KoenVoortman** [comment]
Thank you for the reply. 
I have tried different pins and different leads, but it didn’t do anything else...
So I will try to order another transmitter to try that

**Comment by wibberryd** [comment]
Another idea, but very unlikely: maybe the shutter reached the limit of number of remotes it can register? This limit is around 10 if I recall correctly.

**Comment by KoenVoortman** [comment]
Well, tried a full reset en relearn. 
then I tried to learn the new remote, but still nothing. 

I just got the idea to connect a LED to the data and ground and click some commands. And at every command the led blinks. So the PI is sending data. 

https://user-images.githubusercontent.com/60989130/107883700-b272b380-6ef0-11eb-8f67-49138e449117.mov

So I’ll wait for the new transmitter and try again then...

**Comment by wibberryd** [comment]
If you have a receiver, you can check whether the transmitter is working with a small [set-up like this](https://www.instructables.com/How-to-test-RF-transmitter-and-receiver-before-pro/).

At short distance (< 1m), a 433.92 MHz receiver should be able to receive from a 433.42 MHz transmitter without problem. I've tried with mine and it works.

![IMG_0003](https://user-images.githubusercontent.com/64584934/107958170-ec4fc280-6fa1-11eb-995b-5fc9c68b75eb.jpeg)

**Comment by KoenVoortman** [comment]
Thank you for the tip!

If I am lucky I will receive the transmitter tomorrow so if it doesn’t work I will test this.

**Comment by KoenVoortman** [comment]
I don’t know how long I can take this... :( 

new transmitter, new (same batch) saw resonator. New antenna, new code. Nothing. 

I’ve tested the transmitter to another receiver and the led blinked when command transmitted. 

So maybe (last resort) wrong/bad saw resonators?

**Comment by wibberryd** [comment]
I'm sorry to hear that.

You can try with a new, unmodified transmitter (with original saw resonator and no antenna). The range will be very short (< 2m) and maybe it will not work with some of the shutters. I did this at the beginning, while waiting to receive the 433.42 MHz resonators, and could control most of the shutters when staying at short range from them.

What are the reference of the shutters and remotes? Is it a model where you can also control the tilt angle?

There is a more complex version of the Somfy RTS protocol which allows to control the tilt angle of blinds in addition to the usual up/down motion. I haven't implemented this more complex protocol (also couldn't find any detailed description of this protocol), and I don't know whether this plugin could at least control the up/down movement for those devices, or not.

 I don't have many devices to test the plugin with, and it may be that some configurations are not compatible with the current code. My original remotes are Somfy Smoove Origin RTS:
![prod_450_smoove_pure](https://user-images.githubusercontent.com/64584934/108105622-247fff80-708d-11eb-93cc-2d45913cca9b.jpg)
![images](https://user-images.githubusercontent.com/64584934/108105860-758ff380-708d-11eb-9d1b-49d0c2ee394c.jpeg)

**Comment by KoenVoortman** [comment]
Hi,

thanks again for your extensive reply!
I tried the transmitter for another plugin (KlikAanKlikUit) and it worked fine. So the transmitter is good. I changed that plug-in to the same pin, and it stil worked. So transmitter and PI are good. 

The shutter is what we call a “rolluik” which is an aluminum roller/rolling shutter on the outside of the window/house. 

It was already installed when I bought the house a few years ago, so I don’t know the type. Could be 10 years old or older perhaps. 
the motor and electronics are inside the shutter as far as I know. 

The remote is a basic somfy telis 1 rts pure. 
![2F4DFA13-5F8A-4DE5-ADE2-67E6AD618F4C](https://user-images.githubusercontent.com/60989130/108114578-454e5200-7099-11eb-8d33-18971133fa25.jpeg)

as said before, I did a total reset on the shutter so the memory should be empty. 

I tried high and low id’s but that didn’t make a difference also. 
Maybe there is something wrong with it why it won’t accept another remote. I don’t know anymore....

**Comment by wibberryd** [comment]
Ok, I have similar shutters, and the protocol implemented in this plugin should be compatible with devices controlled by a Telis 1 RTS Pure.

Could you check:
- Which OS/Image have you installed on the Pi:
- pigpio C library version: `apt list pigpio`
- node.js version: `node -v`
- npm version: `npm -v`
- pigpio javascript wrapper: `npm list -g pigpio`
- Homebridge version:
- Homebridge Config-UI-X version:

Could you paste your Homebridge config file? (remove any sensible information)


Could you also try:

- Different values for the ID (in the very unlikely event that your Telis 1 remote has the same ID than configured in Homebridge, or if maybe some ID just don't work for some reason). Try value `1000001` for example if it is not the one that you are using at the moment.

- If it doesn't work, reboot the Pi `sudo reboot`

- If it doesn't work, format the SD card and do a fresh install (or even better: use another SD card to do a fresh install, so you can switch back to the current one at any time)

**Comment by KoenVoortman** [comment]
Okay, strange then...

During al my attempts I've tried various ID's (high and low) and rebooted the pi numerous times.
A clean install can be done... HOOBS or Rasbian and install Homebridge and associated seperately?

As far as I know I'm up-to-date with all versions. Below all the requested information:

apt list pigpio:
Bezig met oplijsten... Klaar
pigpio/testing,now 1.71-0~rpt1 armhf [geïnstalleerd]
N: Er is 1 bijkomende versie. Gebruik schakelaar '-a' om het te zien.

node -v: v14.15.4

npm -v: 7.5.4

npm list -g pigpio:
/usr/lib
└─┬ homebridge-rpi-rts@1.1.1
  └── pigpio@3.3.0

Homebridge v1.1.7

Homebridge UI v4.39.0

Homebridge rpi rts v1.1.1

Linux homebridge 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l

cat /etc/os-release:
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Config.json:

{
    "bridge": {
        "name": "HomeBridge_XXXXX",
        "username": "0A:B3:CD:DF:XX:XX",
        "port": 6XXXX,
        "pin": "0XX-XX-XXX"
    },
    "platforms": [
        {
            "name": "homebridge",
            "port": 8080,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "nl",
            "standalone": true,
            "sessionTimeout": 28800,
            "platform": "config"
        },
        {
            "platform": "KlikAanKlikUit",
            "driver": {
                "type": "rpi",
                "pin": 40
            },
            "accessories": [
                {
                    "name": "Rolluik Achter Links",
                    "type": "Switch",
                    "address": XXXX,
                    "device": 0
                },
                {
                    "name": "Rolluik Achter Rechts",
                    "type": "Switch",
                    "address": XXXX,
                    "device": 1
                },
                {
                    "name": "Zonnescherm Achter",
                    "type": "Switch",
                    "address": XXXX,
                    "device": 2
                },
                {
                    "name": "Zonnescherm Voor",
                    "type": "Switch",
                    "address": XXXX,
                    "device": 3
                }
            ]
        },
        {
            "units": "ca",
            "interval": 15,
            "stations": [
                {
                    "nameNow": "Enschede",
                    "service": "openweathermap",
                    "key": "XXXXXXXXXXXXXXXXXX",
                    "locationGeo": [
                        52.XXXXXXXX,
                        6.XXXXXXX
                    ],
                    "locationCity": "Enschede, NL",
                    "language": "nl",
                    "compatibility": "home",
                    "conditionCategory": "detailed",
                    "now": true,
                    "extraHumidity": false,
                    "hidden": [
                        "Dew Point",
                        "Forecast Day",
                        "Ozone",
                        "Solar Radiation",
                        "Sunrise Time",
                        "Sunset Time"
                    ],
                    "tresholdAirPressure": 1030,
                    "tresholdCloudCover": 75,
                    "tresholdUvIndex": 6,
                    "tresholdWindSpeed": 20
                }
            ],
            "platform": "WeatherPlus"
        },
        {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Voorkant",
                    "manufacturer": "EZ-IP",
                    "model": "IPC-T1A30",
                    "serialNumber": "  4D02C12PAGBDFDA",
                    "firmwareRevision": "2.622.0000000.31.R, Build Date: 2017-12-29",
                    "motion": false,
                    "doorbell": false,
                    "switches": false,
                    "videoConfig": {
                        "source": "-i rtsp://XXXXXXXXXXXXXXXXXXXXX/cam/realmonitor?channel=1&subtype=0",
                        "maxStreams": 2,
                        "maxWidth": 0,
                        "maxHeight": 0,
                        "maxFPS": 30,
                        "maxBitrate": 4069,
                        "packetSize": 1316
                    }
                },
                {
                    "name": "Achterkant",
                    "manufacturer": "EZ-IP",
                    "model": "IPC-T1A30",
                    "serialNumber": "4D02C12PAGBDFDA",
                    "firmwareRevision": "2.622.0000000.31.R, Build Date: 2017-12-29",
                    "motion": false,
                    "switches": false,
                    "videoConfig": {
                        "source": "-i rtsp://XXXXXXXXXXXXXXXXXXXXXXXX/cam/realmonitor?channel=2&subtype=0",
                        "maxStreams": 2,
                        "maxWidth": 0,
                        "maxHeight": 0,
                        "maxFPS": 30,
                        "maxBitrate": 4069,
                        "packetSize": 1316
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
    ],
    "accessories": [
        {
            "name": "Rolluik Voor",
            "id": 138668,
            "prog": true,
            "accessory": "Somfy RTS Remote"
        }
    ]
}

**Comment by wibberryd** [comment]
Package versions and Config.json file look totally correct.

I've just tried to register a new remote on a shutter (with plugin homebridge-rpi-rts v1.1.1), and it works.

Maybe there is an incompatibility between the rpio library used by homebridge-klikaanklikuit and the pigpio library used by homebridge-rpi-rts, or another incompatibility issue between some packages.

If you have a spare SD card, you could try to do a fresh install with the [official Homebridge Raspberry Pi image](https://github.com/homebridge/homebridge-raspbian-image/wiki/Getting-Started).

Node.js, Homebridge, Homebridge-Config-UI-X and pigpio will be already installed.

All you will need to do is:
1. Disable the pigpio daemon service which is running by default on this image: `sudo systemctl disable pigpiod`
2. Restart the Pi
3. Install homebridge-rpi-rts
4. Follow the steps in [Modification of Homebridge Service](https://github.com/wibberryd/homebridge-rpi-rts#modification-of-homebridge-service)
5. Configure the plugin and pair the shutter

**Comment by KoenVoortman** [comment]
Okay, that worked!! 😄 
At first I thought it didn’t, but I had the data on the custom pin. When I put it on gpio 4 it worked!!

now what? How do I get both plugins to work? 🤔

**Comment by nicolasherrbach** [comment]
Great! Happy to hear that :)

I would continue with this fresh install, and try installing the other plugins one by one to see if there is an incompatibility somewhere. Maybe try installing first homebridge-klikaanklikuit as there may be a conflict between their underlaying libraries.

If that works, then continue installing the other plugins.

**Comment by wibberryd** [comment]
Great! Happy to hear that :)

I would continue with this fresh install, and try installing the other plugins one by one to see if there is an incompatibility somewhere. Maybe try installing first homebridge-klikaanklikuit as there may be a conflict between their underlaying libraries.

If that works, then continue installing the other plugins.

**Comment by KoenVoortman** [comment]
Okay, did another clean install... temp card was 32GB 😉 
First time I went too quick and installed all plugins after another... didn't work.
Second time I installed rpi-rts first, did all settings, reboot, and it worked.
Then Klikaanklikuit, settings, reboot, still worked.
And so on, I installed every plugin separately and checked if all still worked.
Now I have setup the new Homebridge in Homekit, and all still seems to work.

Must have been de sequence of installing the plugins (yours and klikaanklikuit in particular) what made them conflict in some way I guess.

Thanks again for al the help and information!! I'm a happy man now! 😄

**Comment by wibberryd** [comment]
This is great news!!

I will close this issue as it looks like the new version also solved the problem with root privilege in Hoobs.

If any other problem arise, feel free to open another issue in GitHub.

Enjoy Homebridge, and have a nice day :)
