### ISSUE TITLE
Signalduino for radio control

### ISSUE THREAD

**Issue by Mazlik1990** [wibberryd/homebridge-rpi-rts#11]
Hey guys, I'm trying to add some blinds to my homebridge right now. 
However, I have a problem with teaching the blinds. The buttons are displayed, but the blind does not move when switching the synchronization.

I use a signalduino for the conversion of the radio signal. I wanted to ask if this works with the signalduino at all?

Here is my setup:
- v1.3.1 Homebridge
- homebridge-rpi-rts v1.1.1
- Signalduino
- Raspberry Pi 4

Thx.

**Comment by wibberryd** [comment]
Hi,
I don't know what a signalduino is? When I search the name on Internet, I find some RF transmitters with USB connector like this:
![SIGNALduino-433-MHz-miniCUL-CC1101-Transceiver](https://user-images.githubusercontent.com/64584934/109352164-aedd1600-787a-11eb-8d2b-3f6daedd131b.jpg)
Is it what you have?

This plugin works with simple RF transmitter connected on the GPIO pins like this:
![cb47a81619e16eb344d89ee03a382dc1](https://user-images.githubusercontent.com/64584934/109352262-cf0cd500-787a-11eb-9f32-776b5027f498.jpg)
They are inexpensive (~ 2 USD on eBay), but it is necessary to replace the resonator by one at 433.42 MHz, which is also quite inexpensive.

I'm sorry, this plugin is not compatible with USB connected RF transmitter.
