### ISSUE TITLE
Help with the hardware

### ISSUE THREAD

**Issue by Nicode70** [wibberryd/homebridge-rpi-rts#13]
Hi! 
I'm startng to build the hardware. I've desoldered the resonator. And the 433.42 is on his way.
But the trouble is that my transmitter module doesn't have the second (smaller) coil. I've drawn it

![IMG_3362](https://user-images.githubusercontent.com/16838672/115357242-bbb42100-a1bc-11eb-9925-1f3664b7608c.jpg)

I can take on that came on the reciever sold with the transmitter. But do i need to?

Also wich port is the antenna port? 1 or 2?

Sorry if my questions are stupid but i'm struggeling to find the answers. And thank you for your help.

**Comment by AragornSRB** [comment]
No2 is for antenna

![image](https://user-images.githubusercontent.com/76788550/116778833-acfb2300-aa74-11eb-8a8e-62012b8cd825.jpeg)

**Comment by Nicode70** [comment]
Thank you very much! Do I need to solder an orange spiral as I drew in the picture? The example picture shows one.

**Comment by AragornSRB** [comment]
No,you see on my picture that only antenna is solderd and transmiter is changed to 433.42.After that just follow instructions for connecting with pi and plugin install

**Comment by Nicode70** [comment]
Thank you very much

**Comment by Nicode70** [comment]
![9686967E-E79E-428B-9B59-6F916F8531BC](https://user-images.githubusercontent.com/16838672/117106601-72e59600-ad80-11eb-996d-4910d50bed20.jpeg)
I’ve been able to complete the soldering, wirering and installation yesterday. It’s so cool. This plugin is terrific. 
it would be better if it could be seen as a shutter in HomeKit, but indo understand that this is a HomeKit limitation. 
anyway thank you very much to anyone involved in this project.
