### ISSUE TITLE
Shutter moves only little when pressing up/down 

### ISSUE THREAD

**Issue by theloi** [wibberryd/homebridge-rpi-rts#19]
Hi and thanks for the plugin as well as the hardware documentation. I have successfully set everything up and it seems to work partially. When I click UP or DOWN in homebridge/homekit the shutter just moves a tiny bit up or down. The "My Prog" button works perfectly. 
I must admit that I did not yet change the resonator to 433.42 MHz yet, because it is currently being shipped. 
Just wanted to ask about/document this phenomenon and will keep you posted as soon as I will have replaced the resonator.
Cheers

**Comment by theloi** [comment]
Hi again. So I replaced the resonator to 4.33.42 MHz, however, the problem still exists. Any hints or hints about how to debug this?

**Comment by RealHaltewunsch** [comment]
Try https://github.com/mwraith/homebridge-somfi-blinds, you can set a "repetitions" to something like 10-15, that fixed it for me.

**Comment by theloi** [comment]
Thanks @RealHaltewunsch, I think the problem might be that my RF Module operates at 9-12V while the raspy can only supply it with by 5V. Where did you guys buy an RF module supporting 5V? ~~Any hints?~~ —> ebay

**Comment by Nicode70** [comment]
I bought this one:
https://www.ebay.fr/itm/263062608815?mkcid=16&mkevt=1&mkrid=709-127639-2357-0&ssspo=NoN9GSADTjm&sssrc=2349624&ssuid=SwnNIdd6Rd6&var=&widget_ver=artemis&media=COPY
and changed this:
https://www.ebay.fr/itm/361865245497?mkcid=16&mkevt=1&mkrid=709-127639-2357-0&ssspo=yXewshl3TuC&sssrc=2349624&ssuid=SwnNIdd6Rd6&var=&widget_ver=artemis&media=COPY

**Comment by RealHaltewunsch** [comment]
Have you @Nicode70 and @theloi updated homebridge to the newest version? I did and I'm not able to use this plugin. In early May the path to the homebridge service changed, see: https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian#configuration-reference.

**Comment by AragornSRB** [comment]
Im on version 1.4.1 and plugin works fine

**Comment by AragornSRB** [comment]
> Thanks @RealHaltewunsch, I think the problem might be that my RF Module operates at 9-12V while the raspy can only supply it with by 5V. Where did you guys buy an RF module supporting 5V? ~~Any hints?~~ —> ebay

https://www.ebay.de/itm/255283295144?mkcid=16&mkevt=1&mkrid=707-127634-2357-0&ssspo=kSLcqpXwSAK&sssrc=2349624&ssuid=rsNFysjqS0C&var=&widget_ver=artemis&media=COPY

https://www.ebay.de/itm/331637441887?mkcid=16&mkevt=1&mkrid=707-127634-2357-0&ssspo=pAEy4doiSe-&sssrc=2349624&ssuid=rsNFysjqS0C&var=&widget_ver=artemis&media=COPY

**Comment by Nicode70** [comment]
> Have you @Nicode70 and @theloi updated homebridge to the newest version? I did and I'm not able to use this plugin. In early May the path to the homebridge service changed, see: https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian#configuration-reference.

I’m up to date and it works just fine

**Comment by theloi** [comment]
Hi @RealHaltewunsch, @Nicode70 and @AragornSRB, thanks for the inputs.  I'm running Homebridge 1.4.1 on a Raspberry Pi Zero W. I bought this RF module: 
https://www.ebay.ch/itm/165451906896?ssPageName=STRK%3AMEBIDX%3AIT&var=465008729031&_trksid=p2060353.m2749.l2648 

and changed to this resonator:
https://www.ebay.ch/itm/331637441887?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2060353.m2749.l2649

But it still does not work. Sometimes the shutter moves, sometimes only a little and then again not at all. I'm out of ideas right now. Any more hints?

**Comment by theloi** [comment]
Hi @RealHaltewunsch, I tried https://github.com/mwraith/homebridge-somfi-blinds set the repetitions to 1 and ... it works. So for this project to continue to work I suggest to add the feature of making the repetitions configurable. It seems that different blinds expect different repetitions.
