### ISSUE TITLE
Error 'Job for homebridge.service failed' after editing Homebridge service files

### ISSUE THREAD

**Issue by Ryamonster10** [wibberryd/homebridge-rpi-rts#2]
After editing the two files, I get this as an error:
Job for homebridge.service failed because the control process exited with error code.
See "systemctl status homebridge.service" and "journalctl -xe" for details.
Don't know what to do about it, any help would be apperated.

**Comment by Ryamonster10** [comment]
Just figured out that you don’t need to do any of that! Just do sudo homebridge and everything will work, no need for adjusting those files!

**Comment by Ryamonster10** [comment]
I just realized that homebridge service is required for the web interface to work which is necessary for normal use.

**Comment by wibberryd** [comment]
Can you provide some info about your environment:
- Raspberry Pi version: 
- OS and version: 
- node.js version: 
- Homebridge version: 


Also check that:

`sudo cat /etc/systemd/system/homebridge.service` gives:
```
[Unit]
Description=Homebridge
Wants=network-online.target
After=syslog.target network-online.target

[Service]
WorkingDirectory=/var/lib/homebridge
EnvironmentFile=/etc/default/homebridge
ExecStartPre=/bin/run-parts /etc/hb-service/homebridge/prestart.d
ExecStartPre=/usr/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js before-start $HOMEBRIDGE_OPTS
ExecStart=/usr/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js run $HOMEBRIDGE_OPTS
# Maybe better to use default KillMode=control-group? Then comment next line.
KillMode=process

[Install]
WantedBy=multi-user.target
```

And `sudo cat /etc/default/homebridge` gives:
```
HOMEBRIDGE_OPTS=-I -U "/var/lib/homebridge" --allow-root
UIX_STORAGE_PATH="/var/lib/homebridge"

# To enable web terminals via homebridge-config-ui-x uncomment the following line
HOMEBRIDGE_CONFIG_UI_TERMINAL=1

DISABLE_OPENCOLLECTIVE=true
```

**Comment by Ryamonster10** [comment]
I don know what you mean by Raspberry PI version. but I am running the home bridge on raspberry pi image (https://github.com/homebridge/homebridge-raspbian-image) 
OS: https://github.com/homebridge/homebridge-raspbian-image (v1.0.17) (Lastest)
Homebridge version: v1.0.17
Node.JS version:  v14.15.1
And yes, both those commands return thoses.

**Comment by Ryamonster10** [comment]
I am using sudo nano to edit the files in SSH, if that helps. @wibberryd Not sure if it makes a difference but what command line script did you use to edit files?

**Comment by wibberryd** [comment]
I am also running Node.js v14.15 and Homebridge v1.0.17, and used nano to edit the two files.

Which model of Raspberry are you using?

**Comment by Ryamonster10** [comment]
Raspberry Pi 3 Model B 
<img width="493" alt="Screen Shot 2021-01-23 at 3 40 19 PM" src="https://user-images.githubusercontent.com/45019531/105613584-628d4a80-5d91-11eb-82b9-bf524d79c857.png">

**Comment by Ryamonster10** [comment]
<img width="1440" alt="Screen Shot 2021-01-23 at 3 38 12 PM" src="https://user-images.githubusercontent.com/45019531/105613524-104c2980-5d91-11eb-90af-d34ef57ad173.png">
That is what happens on my Raspberry Pi 3 Model B V1.2

**Comment by Ryamonster10** [comment]
That is what happens on my Raspberry Pi 3 Model B V1.2

**Comment by schweppy** [comment]
Same error for me after editing the 2 files using nano on my Pi4. I also use the official homebridge raspbian image. 

Any ideas?

**Comment by schweppy** [comment]
My systemctl error - 

`Jan 31 14:42:42 homebridge run-parts[696]: Reloading nginx...
Jan 31 14:42:43 homebridge systemd[715]: homebridge.service: Failed to executJan 31 14:42:43 homebridge systemd[715]: homebridge.service: Failed at step EJan 31 14:42:43 homebridge systemd[1]: homebridge.service: Control process exJan 31 14:42:43 homebridge systemd[1]: homebridge.service: Failed with resultJan 31 14:42:43 homebridge systemd[1]: Failed to start Homebridge. `

**Comment by schweppy** [comment]
Systemctl errors - 

homebridge.service:Failed to execute command: No such file or directory

homebridge.service: Failed at step EXEC spawning /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.

**Comment by wibberryd** [comment]
I did some tests on the latest official Homebridge Rasbian image (1.0.18) on a Raspberry Pi 4 B, and got it working with the following changes:

In the file `/etc/systemd/system/homebridge.service`:

Change `User=pi` to `User=root`

And delete the line:
```
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_CHOWN CAP_FOWNER CAP_DAC_OVERRIDE CAP_AUDIT_WRITE CAP_SYS_ADMIN
AmbientCapabilities=CAP_NET_RAW CAP_NET_BIND_SERVICE
```

So the final file should be:
```
[Unit]
Description=Homebridge
Wants=network-online.target
After=syslog.target network-online.target

[Service]
Type=simple
User=root
PermissionsStartOnly=true
WorkingDirectory=/var/lib/homebridge
EnvironmentFile=/etc/default/homebridge
ExecStartPre=-run-parts /etc/hb-service/homebridge/prestart.d
ExecStartPre=-/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js before-start $HOMEBRIDGE_OPTS
ExecStart=/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js run $HOMEBRIDGE_OPTS
Restart=always
RestartSec=3
KillMode=process

[Install]
WantedBy=multi-user.target
```

Then `sudo systemctl daemon-reload` and `sudo hb-service restart`.

Also, I got the error `Can't lock /var/run/pigpio.pid`, which was solved with the command `sudo killall pigpiod`. (pigpio cannot lock this resource from the Homebridge plugin if a pigpio daemon has already locked it previously, which was the case for me with the official Homebridge Raspbian image).

**Comment by schweppy** [comment]
Yep that looks to have sorted it. 😊 many thanks!

**Comment by Ryamonster10** [comment]
Thank you so much! This totally worked!
