### ISSUE TITLE
Instructions for running homebridge as root are out of date

### ISSUE THREAD

**Issue by conradlee** [wibberryd/homebridge-rpi-rts#22]
In early May 2022 Homebridge [changed some paths](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian#configuration-reference). So if you're using a newer version of homebridge,  the instructions in `README.md` no longer work.

I've found a solution...The steps you now need to take to run homebridge as root are as follows:
1. From the command line, run `sudo systemctl edit homebridge`.
2. Change the configuration file to the following
```
[Service]
User=root
ExecStart=    # a blank ExecStart is required to override
ExecStart=/opt/homebridge/start.sh --allow-root
```
Then save the file and exit the editor.

3. Now restart homebridge by running `sudo systemctl restart homebridge`

**Comment by conradlee** [comment]
I've created a PR to update the docs with these instructions [here](https://github.com/wibberryd/homebridge-rpi-rts/pull/21/files).

**Comment by wibberryd** [comment]
PR merged. Thank you!
