### ISSUE TITLE
Up / Down / My buttons now all have same name

### ISSUE THREAD

**Issue by conradlee** [wibberryd/homebridge-rpi-rts#23]
I've noticed that a given accessory's Up / Down / My buttons now all have same name.   This wasn't true before -- I am not sure what changed.  Here's what it now looks like (notice how each accessory has three buttons and there's no way to know which is responsible for up/down/my.

![IMG_7C57747ACA16-1](https://user-images.githubusercontent.com/230949/202997297-dc6a966d-1dc3-421d-a0f6-b5b57b95c5a3.jpeg)

**Comment by conradlee** [comment]
Perhaps this problem arose after updating my home app on my phone (which happened when I upgraded to iOS 16).  The problem also arises when viewing the accessories in the Eve Home app.  The screenshot above is from the Eve home app.

**Comment by conradlee** [comment]
Also note that I can work around this by experimenting with each button to see what it does empirically, and then renaming that button in the Home app with an appropriate name.

**Comment by wibberryd** [comment]
Probably linked with changes in iOS 16 / macOS 13 according to my own experience and search results on Internet.

A workaround is to go to the Home App, open the device's settings and click (x) next to the device's name. The original name will appear as a suggestion.
