### ISSUE TITLE
Error 'TypeError [ERR_INVALID_ARG_TYPE]' when pressing a button

### ISSUE THREAD

**Issue by AragornSRB** [wibberryd/homebridge-rpi-rts#3]
I managed to install plugin on hoobs and when i start programing remote hub shut down after shutter react :(.Im getting erorr 

 TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (2) at Object.writeFile (fs.js:1436:5)
sigHandler: Unhandled signal 15, terminating

Please help :)

**Comment by wibberryd** [comment]
The version 1.0.2 should solve this issue. Can you try to update and see if it solves your problem?

**Comment by AragornSRB** [comment]
It works perfectly now!!!Thanks  :))))))

**Comment by wibberryd** [comment]
I am very glad to hear that! :)

**Comment by Ryamonster10** [comment]
Now a different error is showing up that was not before this update.
